[package]
name = "poll"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.2"
lambda_http = "0.1"
serde_json = "1.0"

[[bin]]
name = "command"
path = "src/command.rs"

[[bin]]
name = "interaction"
path = "src/interaction.rs"
